Ext.define('atm_recon.constant.ActionType', {
	alias: 'appActionType',
	alternateClassName: 'appActionType',
	statics: {
		ACTION_TYPE_NEW: 'NEW',
		ACTION_TYPE_UPDATE: 'UPDATE',
		ACTION_TYPE_SELECT: 'SELECT',
		ACTION_TYPE_LOGIN: 'LOGIN',
		ACTION_TYPE_LOGOUT: 'LOGOUT',
		ACTION_TYPE_SELECT_DISPUTE: 'SELECT_DISPUTE',
		ACTION_TYPE_EXPORT_DISPUTE: 'EXPORT_DISPUTE_EXCEL',
		ACTION_TYPE_EXPORT_COMPLAINT: 'EXPORT_EXCEL',
		ACTION_TYPE_SELECT_ATM: 'SELECT_ATM',
		ACTION_TYPE_SELECT_STATES: 'SELECT_STATES',
		ACTION_TYPE_SELECT_NPSB: 'SELECT_NPSB',
		ACTION_TYPE_SELECT_CBS_DATA: 'SELECT_CBS_DATA',
		ACTION_TYPE_SELECT_DASHBOARD_DATA: 'SELECT_RECENT_COMPLAINT',
		ACTION_TYPE_SELECT_DASHBOARD_TODAY: 'SELECT_TODAYS_DATA',
		ACTION_TYPE_SELECT_ACCSTATEMENT_DATA: 'STATEMENT_DATA',
	}
});